#!/bin/bash
if [ -z "$CI" ]; then echo "Not CI environment, exiting." && exit; fi
if [ -z "$GITHUB_SHA" ]; then echo "GITHUB_SHA not set, exiting." && exit; fi
if ! [ -x "$(command -v sentry-cli)" ]; then
  echo "sentry-cli is not installed; installing."
  curl -sL https://sentry.io/get-cli/ | bash
fi
export SENTRY_ORG=getbaseline
export SENTRY_PROJECT=baseline
sentry-cli sourcemaps inject build/static/js
sentry-cli sourcemaps upload --release=$GITHUB_SHA --url-prefix="~/static/js" --validate build/static/js