#page title
page_title                                : baseline

# App Info
ios_app_id                                : 1621132298
ios_app_country                           : us

appstore_link                             :
playstore_link                            :

wide_word_mark                            : assets/widewordmark.png
word_mark                                 : assets/wordmark.png
word_mark_dark                            : assets/wordmarkdark.png
app_description                           : A better journaling and mood tracking app.

enable_smart_app_banner                   : true

features                                  :

  - title                                 : Understand your brain.
    description                           : By mood logging, you'll start to get a better feel for who you are and what you need to become healthier.
    fontawesome_icon_name                 : pencil

  - title                                 : Keep a schedule.
    description                           : Set granular notifications to keep yourself accountable to your mental health goals.
    fontawesome_icon_name                 : calendar-days

  - title                                 : Recap your week.
    description                           : At the end of each week, you'll get a chance to take some mental health surveys and review your overall health baseline.
    fontawesome_icon_name                 : backward

  - title                                 : Keep private thoughts private.
    description                           : You can set a passphrase in-app to hide your data from people who might have access to your device.
    fontawesome_icon_name                 : key

  - title                                 : Track your progress.
    description                           : baseline has visualizations to help you better understand how your mood changes over time. 
    fontawesome_icon_name                 : chart-line

  - title                                 : Lock your data away.
    description                           : We encrypt your data so that not even we can see it, let alone anyone else.
    fontawesome_icon_name                 : lock

# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.2
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.jpg
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"

####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
