# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    setup_ci if ENV['CI']
    match(type: "appstore")
    increment_build_number({
      build_number: latest_testflight_build_number(api_key_path: "authkey.json") + 1
    })
    build_app(workspace: "App.xcworkspace", scheme: "App")
    set_changelog
    upload_to_testflight(
      api_key_path: "authkey.json", 
      skip_waiting_for_build_processing: true, 
      changelog: "Upload from GitHub Actions, ref #{ENV['GITHUB_REF']}, sha #{ENV['GITHUB_SHA']}"
    )
  end
end
