name: Deploy Internal Services

on:
  push:
    branches:
      - main
    paths:
      - "scheduled-services/**"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scheduled-services
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Use Node.js 18
      uses: actions/setup-node@v4
      with:
        node-version: "18.x"
        cache: "npm"
    - run: npm ci
    - run: npm run build
    - name: Deploy to Cloud Run
      run: |
        echo $GOOGLE_APPLICATION_CREDENTIALS > ~/google-credentials.json
        gcloud auth activate-service-account --key-file ~/google-credentials.json
        npm run deploy
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_GETBASELINEAPP }}
